source 'https://rubygems.org'

gem 'cuba'
gem 'faraday', '0.8.10'
gem 'mongoid', '5.0.0'
gem 'mongoid-paperclip', require: 'mongoid_paperclip'
gem 'aws-sdk', '< 2.0'
gem 'mote'
gem 'mote-render'
gem 'puma'
gem 'send_file'
gem 'autocode'
