production:
  image_endpoint: images/(.+)\/?\z
  url: /images/:id
  storage:
    path: /rixel-drop
    s3:
      path: /images/:id
      bucket_name: S3_BUCKET_NAME
      s3_credentials:
        access_key_id: ACCESS_KEY_ID
        secret_access_key: SECRET_ACCESS_KEY
      cache:
        max_size: 40g
  max_size:
    width: 1000
    height: 1000
  labels:
    default:
      size: 40
      border_color: black
      border_size: 1
      color: white
      font: Impact
    available_fonts:
      - Impact
      - Times
  imagemagick:
    convert: /usr/local/bin/convert
    identify: /usr/local/bin/identify
  imgmin_path: /usr/local/bin/imgmin
